### ISSUE TITLE
ImageMagick warnings

### ISSUE THREAD

**Issue by norm** [reevoo/spriter#2]
(sinister sites/world :*+)% ./bauhaus/sprites/build 
Warning: MiniMagick::Image.from_file is now deprecated. Please use Image.open
Warning: MiniMagick::Image.from_file is now deprecated. Please use Image.open

Using deprecated features makes panda sad.

**Comment by jonnyarnold** [comment]
This gem is no longer in active development by Reevoo. If you would like to make an update, please feel free to send us a pull request for review.
